import {
	getABook,
	getAllBooks,
	getAGenreBooks,
	searchBook,
	filterProducts,
	getOrders,
	getUserDetail,
	updateUserDetail,
	getWishlist,
	updateWishlist,
	getCartItems,
	updateCart,
	addBookSubscription,
	getBookSubscription
} from './user.controller';
import {signInUser, signUpUser, signOutUser} from './auth.controller';
import {
	adminSearchBook,
	adminAddBook,
	adminAddBookSubscription,
	adminDeleteBook,
	adminGetBook,
	adminGetBooks,
	adminGetDonations,
	adminGetGenreBooks,
	adminGetOrders,
	adminGetSubscriptions,
	adminGetUser,
	adminGetUserBookSubscriptions,
	adminGetUserCartItems,
	adminGetUserDonations,
	adminGetUserOrder,
	adminUpdateBook,
	adminGetUsers
} from './admin.controller';

const controllerContainer = {
	signInUser,
	signUpUser,
	signOutUser,
	getABook,
	getAllBooks,
	getAGenreBooks,
	searchBook,
	filterProducts,
	getOrders,
	getUserDetail,
	updateUserDetail,
	getWishlist,
	updateWishlist,
	getCartItems,
	updateCart,
	addBookSubscription,
	getBookSubscription,
	adminSearchBook,
	adminAddBook,
	adminAddBookSubscription,
	adminDeleteBook,
	adminGetBook,
	adminGetBooks,
	adminGetDonations,
	adminGetGenreBooks,
	adminGetOrders,
	adminGetSubscriptions,
	adminGetUser,
	adminGetUsers,
	adminGetUserBookSubscriptions,
	adminGetUserCartItems,
	adminGetUserDonations,
	adminGetUserOrder,
	adminUpdateBook
};

export {controllerContainer};
