import {
	getABookService,
	getAllBooksService,
	getAGenreBooksService,
	searchService,
	getOrdersService,
	getUserDetailService,
	updateUserDetailService,
	getWishlistService,
	updateWishlistService,
	getCartItemsService,
	updateCartService,
	addBookSubscriptionService,
	getBookSubscriptionService
} from './user.service';
import {signInUserService, signUpUserService} from './auth.service';
import {
	adminSearchService,
	adminAddBookService,
	adminDeleteBookService,
	adminGetBookService,
	adminGetBooksService,
	adminGetDonationsService,
	adminGetGenreBooksService,
	adminGetOrdersService,
	adminGetSubscriptionsService,
	adminGetUserBookSubscriptionsService,
	adminGetUserCartItemsService,
	adminGetUserDonationsService,
	adminGetUserOrdersService,
	adminGetUserService,
	adminGetUsersService,
	adminSearchBookService,
	adminUpdateBookService
} from './admin.service';

const serviceContainer = {
	signInUserService,
	signUpUserService,
	getABookService,
	getAllBooksService,
	getAGenreBooksService,
	searchService,
	getOrdersService,
	getUserDetailService,
	updateUserDetailService,
	getWishlistService,
	updateWishlistService,
	getCartItemsService,
	updateCartService,
	addBookSubscriptionService,
	getBookSubscriptionService,
	adminSearchService,
	adminAddBookService,
	adminDeleteBookService,
	adminGetBookService,
	adminGetBooksService,
	adminGetDonationsService,
	adminGetGenreBooksService,
	adminGetOrdersService,
	adminGetSubscriptionsService,
	adminGetUserBookSubscriptionsService,
	adminGetUserCartItemsService,
	adminGetUserDonationsService,
	adminGetUserOrdersService,
	adminGetUserService,
	adminSearchBookService,
	adminUpdateBookService,
	adminGetUsersService
};

export {serviceContainer};
